// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: snaphaven/snaphaven.proto

package snaphaven

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientVersion string `protobuf:"bytes,1,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"`
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_snaphaven_snaphaven_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_snaphaven_snaphaven_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_snaphaven_snaphaven_proto_rawDescGZIP(), []int{0}
}

func (x *PingRequest) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

type PingReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerVersion string `protobuf:"bytes,1,opt,name=server_version,json=serverVersion,proto3" json:"server_version,omitempty"`
	ServerTimeMs  int64  `protobuf:"varint,2,opt,name=server_time_ms,json=serverTimeMs,proto3" json:"server_time_ms,omitempty"`
}

func (x *PingReply) Reset() {
	*x = PingReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_snaphaven_snaphaven_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingReply) ProtoMessage() {}

func (x *PingReply) ProtoReflect() protoreflect.Message {
	mi := &file_snaphaven_snaphaven_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingReply.ProtoReflect.Descriptor instead.
func (*PingReply) Descriptor() ([]byte, []int) {
	return file_snaphaven_snaphaven_proto_rawDescGZIP(), []int{1}
}

func (x *PingReply) GetServerVersion() string {
	if x != nil {
		return x.ServerVersion
	}
	return ""
}

func (x *PingReply) GetServerTimeMs() int64 {
	if x != nil {
		return x.ServerTimeMs
	}
	return 0
}

type FileInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Hash string `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (x *FileInfoRequest) Reset() {
	*x = FileInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_snaphaven_snaphaven_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfoRequest) ProtoMessage() {}

func (x *FileInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_snaphaven_snaphaven_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfoRequest.ProtoReflect.Descriptor instead.
func (*FileInfoRequest) Descriptor() ([]byte, []int) {
	return file_snaphaven_snaphaven_proto_rawDescGZIP(), []int{2}
}

func (x *FileInfoRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileInfoRequest) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

type FileInfoReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path          string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Hash          string `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	Shouldsend    bool   `protobuf:"varint,3,opt,name=shouldsend,proto3" json:"shouldsend,omitempty"`
	NeedThumbnail bool   `protobuf:"varint,4,opt,name=need_thumbnail,json=needThumbnail,proto3" json:"need_thumbnail,omitempty"`
}

func (x *FileInfoReply) Reset() {
	*x = FileInfoReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_snaphaven_snaphaven_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileInfoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfoReply) ProtoMessage() {}

func (x *FileInfoReply) ProtoReflect() protoreflect.Message {
	mi := &file_snaphaven_snaphaven_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfoReply.ProtoReflect.Descriptor instead.
func (*FileInfoReply) Descriptor() ([]byte, []int) {
	return file_snaphaven_snaphaven_proto_rawDescGZIP(), []int{3}
}

func (x *FileInfoReply) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileInfoReply) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *FileInfoReply) GetShouldsend() bool {
	if x != nil {
		return x.Shouldsend
	}
	return false
}

func (x *FileInfoReply) GetNeedThumbnail() bool {
	if x != nil {
		return x.NeedThumbnail
	}
	return false
}

type FileChunk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path     string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Contents []byte `protobuf:"bytes,2,opt,name=contents,proto3" json:"contents,omitempty"`
}

func (x *FileChunk) Reset() {
	*x = FileChunk{}
	if protoimpl.UnsafeEnabled {
		mi := &file_snaphaven_snaphaven_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileChunk) ProtoMessage() {}

func (x *FileChunk) ProtoReflect() protoreflect.Message {
	mi := &file_snaphaven_snaphaven_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileChunk.ProtoReflect.Descriptor instead.
func (*FileChunk) Descriptor() ([]byte, []int) {
	return file_snaphaven_snaphaven_proto_rawDescGZIP(), []int{4}
}

func (x *FileChunk) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileChunk) GetContents() []byte {
	if x != nil {
		return x.Contents
	}
	return nil
}

type FileReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path     string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Received bool   `protobuf:"varint,2,opt,name=received,proto3" json:"received,omitempty"`
}

func (x *FileReply) Reset() {
	*x = FileReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_snaphaven_snaphaven_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileReply) ProtoMessage() {}

func (x *FileReply) ProtoReflect() protoreflect.Message {
	mi := &file_snaphaven_snaphaven_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileReply.ProtoReflect.Descriptor instead.
func (*FileReply) Descriptor() ([]byte, []int) {
	return file_snaphaven_snaphaven_proto_rawDescGZIP(), []int{5}
}

func (x *FileReply) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileReply) GetReceived() bool {
	if x != nil {
		return x.Received
	}
	return false
}

type ListFilesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Prefix    string `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Folder    string `protobuf:"bytes,2,opt,name=folder,proto3" json:"folder,omitempty"`
	Recursive bool   `protobuf:"varint,3,opt,name=recursive,proto3" json:"recursive,omitempty"`
}

func (x *ListFilesRequest) Reset() {
	*x = ListFilesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_snaphaven_snaphaven_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListFilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesRequest) ProtoMessage() {}

func (x *ListFilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_snaphaven_snaphaven_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesRequest.ProtoReflect.Descriptor instead.
func (*ListFilesRequest) Descriptor() ([]byte, []int) {
	return file_snaphaven_snaphaven_proto_rawDescGZIP(), []int{6}
}

func (x *ListFilesRequest) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *ListFilesRequest) GetFolder() string {
	if x != nil {
		return x.Folder
	}
	return ""
}

func (x *ListFilesRequest) GetRecursive() bool {
	if x != nil {
		return x.Recursive
	}
	return false
}

type RemoteFileItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path         string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Filename     string `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	Size         int64  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	ModTimeMs    int64  `protobuf:"varint,4,opt,name=mod_time_ms,json=modTimeMs,proto3" json:"mod_time_ms,omitempty"`
	IsVideo      bool   `protobuf:"varint,5,opt,name=is_video,json=isVideo,proto3" json:"is_video,omitempty"`
	Sha256       string `protobuf:"bytes,6,opt,name=sha256,proto3" json:"sha256,omitempty"`
	HasThumbnail bool   `protobuf:"varint,7,opt,name=has_thumbnail,json=hasThumbnail,proto3" json:"has_thumbnail,omitempty"`
	Folder       string `protobuf:"bytes,8,opt,name=folder,proto3" json:"folder,omitempty"`
}

func (x *RemoteFileItem) Reset() {
	*x = RemoteFileItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_snaphaven_snaphaven_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoteFileItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteFileItem) ProtoMessage() {}

func (x *RemoteFileItem) ProtoReflect() protoreflect.Message {
	mi := &file_snaphaven_snaphaven_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteFileItem.ProtoReflect.Descriptor instead.
func (*RemoteFileItem) Descriptor() ([]byte, []int) {
	return file_snaphaven_snaphaven_proto_rawDescGZIP(), []int{7}
}

func (x *RemoteFileItem) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *RemoteFileItem) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *RemoteFileItem) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *RemoteFileItem) GetModTimeMs() int64 {
	if x != nil {
		return x.ModTimeMs
	}
	return 0
}

func (x *RemoteFileItem) GetIsVideo() bool {
	if x != nil {
		return x.IsVideo
	}
	return false
}

func (x *RemoteFileItem) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *RemoteFileItem) GetHasThumbnail() bool {
	if x != nil {
		return x.HasThumbnail
	}
	return false
}

func (x *RemoteFileItem) GetFolder() string {
	if x != nil {
		return x.Folder
	}
	return ""
}

type ListFilesReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Files   []*RemoteFileItem `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	Folders []string          `protobuf:"bytes,2,rep,name=folders,proto3" json:"folders,omitempty"`
}

func (x *ListFilesReply) Reset() {
	*x = ListFilesReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_snaphaven_snaphaven_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListFilesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesReply) ProtoMessage() {}

func (x *ListFilesReply) ProtoReflect() protoreflect.Message {
	mi := &file_snaphaven_snaphaven_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesReply.ProtoReflect.Descriptor instead.
func (*ListFilesReply) Descriptor() ([]byte, []int) {
	return file_snaphaven_snaphaven_proto_rawDescGZIP(), []int{8}
}

func (x *ListFilesReply) GetFiles() []*RemoteFileItem {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *ListFilesReply) GetFolders() []string {
	if x != nil {
		return x.Folders
	}
	return nil
}

type ThumbnailRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path   string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Sha256 string `protobuf:"bytes,2,opt,name=sha256,proto3" json:"sha256,omitempty"`
}

func (x *ThumbnailRequest) Reset() {
	*x = ThumbnailRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_snaphaven_snaphaven_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ThumbnailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThumbnailRequest) ProtoMessage() {}

func (x *ThumbnailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_snaphaven_snaphaven_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThumbnailRequest.ProtoReflect.Descriptor instead.
func (*ThumbnailRequest) Descriptor() ([]byte, []int) {
	return file_snaphaven_snaphaven_proto_rawDescGZIP(), []int{9}
}

func (x *ThumbnailRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ThumbnailRequest) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

type ThumbnailReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path     string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Data     []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	MimeType string `protobuf:"bytes,3,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	Found    bool   `protobuf:"varint,4,opt,name=found,proto3" json:"found,omitempty"`
}

func (x *ThumbnailReply) Reset() {
	*x = ThumbnailReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_snaphaven_snaphaven_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ThumbnailReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThumbnailReply) ProtoMessage() {}

func (x *ThumbnailReply) ProtoReflect() protoreflect.Message {
	mi := &file_snaphaven_snaphaven_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThumbnailReply.ProtoReflect.Descriptor instead.
func (*ThumbnailReply) Descriptor() ([]byte, []int) {
	return file_snaphaven_snaphaven_proto_rawDescGZIP(), []int{10}
}

func (x *ThumbnailReply) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ThumbnailReply) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ThumbnailReply) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *ThumbnailReply) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type UploadThumbnailRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path     string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Sha256   string `protobuf:"bytes,2,opt,name=sha256,proto3" json:"sha256,omitempty"`
	Data     []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	MimeType string `protobuf:"bytes,4,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
}

func (x *UploadThumbnailRequest) Reset() {
	*x = UploadThumbnailRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_snaphaven_snaphaven_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadThumbnailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadThumbnailRequest) ProtoMessage() {}

func (x *UploadThumbnailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_snaphaven_snaphaven_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadThumbnailRequest.ProtoReflect.Descriptor instead.
func (*UploadThumbnailRequest) Descriptor() ([]byte, []int) {
	return file_snaphaven_snaphaven_proto_rawDescGZIP(), []int{11}
}

func (x *UploadThumbnailRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *UploadThumbnailRequest) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *UploadThumbnailRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UploadThumbnailRequest) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

type UploadThumbnailReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *UploadThumbnailReply) Reset() {
	*x = UploadThumbnailReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_snaphaven_snaphaven_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadThumbnailReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadThumbnailReply) ProtoMessage() {}

func (x *UploadThumbnailReply) ProtoReflect() protoreflect.Message {
	mi := &file_snaphaven_snaphaven_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadThumbnailReply.ProtoReflect.Descriptor instead.
func (*UploadThumbnailReply) Descriptor() ([]byte, []int) {
	return file_snaphaven_snaphaven_proto_rawDescGZIP(), []int{12}
}

func (x *UploadThumbnailReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type MediaRangeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path      string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	StartByte int64  `protobuf:"varint,2,opt,name=start_byte,json=startByte,proto3" json:"start_byte,omitempty"`
	Length    int64  `protobuf:"varint,3,opt,name=length,proto3" json:"length,omitempty"`
}

func (x *MediaRangeRequest) Reset() {
	*x = MediaRangeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_snaphaven_snaphaven_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MediaRangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaRangeRequest) ProtoMessage() {}

func (x *MediaRangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_snaphaven_snaphaven_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaRangeRequest.ProtoReflect.Descriptor instead.
func (*MediaRangeRequest) Descriptor() ([]byte, []int) {
	return file_snaphaven_snaphaven_proto_rawDescGZIP(), []int{13}
}

func (x *MediaRangeRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *MediaRangeRequest) GetStartByte() int64 {
	if x != nil {
		return x.StartByte
	}
	return 0
}

func (x *MediaRangeRequest) GetLength() int64 {
	if x != nil {
		return x.Length
	}
	return 0
}

type MediaChunk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Offset    int64  `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Data      []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	TotalSize int64  `protobuf:"varint,3,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
}

func (x *MediaChunk) Reset() {
	*x = MediaChunk{}
	if protoimpl.UnsafeEnabled {
		mi := &file_snaphaven_snaphaven_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MediaChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaChunk) ProtoMessage() {}

func (x *MediaChunk) ProtoReflect() protoreflect.Message {
	mi := &file_snaphaven_snaphaven_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaChunk.ProtoReflect.Descriptor instead.
func (*MediaChunk) Descriptor() ([]byte, []int) {
	return file_snaphaven_snaphaven_proto_rawDescGZIP(), []int{14}
}

func (x *MediaChunk) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *MediaChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *MediaChunk) GetTotalSize() int64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

type DownloadFileRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *DownloadFileRequest) Reset() {
	*x = DownloadFileRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_snaphaven_snaphaven_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DownloadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadFileRequest) ProtoMessage() {}

func (x *DownloadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_snaphaven_snaphaven_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadFileRequest.ProtoReflect.Descriptor instead.
func (*DownloadFileRequest) Descriptor() ([]byte, []int) {
	return file_snaphaven_snaphaven_proto_rawDescGZIP(), []int{15}
}

func (x *DownloadFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type VerifyItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path   string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Size   int64  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Sha256 string `protobuf:"bytes,3,opt,name=sha256,proto3" json:"sha256,omitempty"`
}

func (x *VerifyItem) Reset() {
	*x = VerifyItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_snaphaven_snaphaven_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyItem) ProtoMessage() {}

func (x *VerifyItem) ProtoReflect() protoreflect.Message {
	mi := &file_snaphaven_snaphaven_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyItem.ProtoReflect.Descriptor instead.
func (*VerifyItem) Descriptor() ([]byte, []int) {
	return file_snaphaven_snaphaven_proto_rawDescGZIP(), []int{16}
}

func (x *VerifyItem) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *VerifyItem) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *VerifyItem) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

type VerifyFilesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*VerifyItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *VerifyFilesRequest) Reset() {
	*x = VerifyFilesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_snaphaven_snaphaven_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyFilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyFilesRequest) ProtoMessage() {}

func (x *VerifyFilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_snaphaven_snaphaven_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyFilesRequest.ProtoReflect.Descriptor instead.
func (*VerifyFilesRequest) Descriptor() ([]byte, []int) {
	return file_snaphaven_snaphaven_proto_rawDescGZIP(), []int{17}
}

func (x *VerifyFilesRequest) GetItems() []*VerifyItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type VerifiedResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path        string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Exists      bool   `protobuf:"varint,2,opt,name=exists,proto3" json:"exists,omitempty"`
	SizeMatches bool   `protobuf:"varint,3,opt,name=size_matches,json=sizeMatches,proto3" json:"size_matches,omitempty"`
	HashMatches bool   `protobuf:"varint,4,opt,name=hash_matches,json=hashMatches,proto3" json:"hash_matches,omitempty"`
}

func (x *VerifiedResult) Reset() {
	*x = VerifiedResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_snaphaven_snaphaven_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifiedResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifiedResult) ProtoMessage() {}

func (x *VerifiedResult) ProtoReflect() protoreflect.Message {
	mi := &file_snaphaven_snaphaven_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifiedResult.ProtoReflect.Descriptor instead.
func (*VerifiedResult) Descriptor() ([]byte, []int) {
	return file_snaphaven_snaphaven_proto_rawDescGZIP(), []int{18}
}

func (x *VerifiedResult) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *VerifiedResult) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

func (x *VerifiedResult) GetSizeMatches() bool {
	if x != nil {
		return x.SizeMatches
	}
	return false
}

func (x *VerifiedResult) GetHashMatches() bool {
	if x != nil {
		return x.HashMatches
	}
	return false
}

type VerifyFilesReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Results []*VerifiedResult `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
}

func (x *VerifyFilesReply) Reset() {
	*x = VerifyFilesReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_snaphaven_snaphaven_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyFilesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyFilesReply) ProtoMessage() {}

func (x *VerifyFilesReply) ProtoReflect() protoreflect.Message {
	mi := &file_snaphaven_snaphaven_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyFilesReply.ProtoReflect.Descriptor instead.
func (*VerifyFilesReply) Descriptor() ([]byte, []int) {
	return file_snaphaven_snaphaven_proto_rawDescGZIP(), []int{19}
}

func (x *VerifyFilesReply) GetResults() []*VerifiedResult {
	if x != nil {
		return x.Results
	}
	return nil
}

var File_snaphaven_snaphaven_proto protoreflect.FileDescriptor

var file_snaphaven_snaphaven_proto_rawDesc = []byte{
	0x0a, 0x19, 0x73, 0x6e, 0x61, 0x70, 0x68, 0x61, 0x76, 0x65, 0x6e, 0x2f, 0x73, 0x6e, 0x61, 0x70,
	0x68, 0x61, 0x76, 0x65, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x73, 0x6e, 0x61,
	0x70, 0x68, 0x61, 0x76, 0x65, 0x6e, 0x22, 0x34, 0x0a, 0x0b, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x58, 0x0a, 0x09,
	0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x25, 0x0a, 0x0e, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x12, 0x24, 0x0a, 0x0e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x5f,
	0x6d, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x54, 0x69, 0x6d, 0x65, 0x4d, 0x73, 0x22, 0x39, 0x0a, 0x0f, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74,
	0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x12, 0x0a,
	0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x61, 0x73,
	0x68, 0x22, 0x7e, 0x0a, 0x0d, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x68,
	0x6f, 0x75, 0x6c, 0x64, 0x73, 0x65, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a,
	0x73, 0x68, 0x6f, 0x75, 0x6c, 0x64, 0x73, 0x65, 0x6e, 0x64, 0x12, 0x25, 0x0a, 0x0e, 0x6e, 0x65,
	0x65, 0x64, 0x5f, 0x74, 0x68, 0x75, 0x6d, 0x62, 0x6e, 0x61, 0x69, 0x6c, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x0d, 0x6e, 0x65, 0x65, 0x64, 0x54, 0x68, 0x75, 0x6d, 0x62, 0x6e, 0x61, 0x69,
	0x6c, 0x22, 0x3b, 0x0a, 0x09, 0x46, 0x69, 0x6c, 0x65, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x12, 0x12,
	0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61,
	0x74, 0x68, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x3b,
	0x0a, 0x09, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x70,
	0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12,
	0x1a, 0x0a, 0x08, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x08, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x64, 0x22, 0x60, 0x0a, 0x10, 0x4c,
	0x69, 0x73, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x6f, 0x6c, 0x64, 0x65,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x12,
	0x1c, 0x0a, 0x09, 0x72, 0x65, 0x63, 0x75, 0x72, 0x73, 0x69, 0x76, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x09, 0x72, 0x65, 0x63, 0x75, 0x72, 0x73, 0x69, 0x76, 0x65, 0x22, 0xe4, 0x01,
	0x0a, 0x0e, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x74, 0x65, 0x6d,
	0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x70, 0x61, 0x74, 0x68, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04,
	0x73, 0x69, 0x7a, 0x65, 0x12, 0x1e, 0x0a, 0x0b, 0x6d, 0x6f, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65,
	0x5f, 0x6d, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x6d, 0x6f, 0x64, 0x54, 0x69,
	0x6d, 0x65, 0x4d, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x69, 0x73, 0x5f, 0x76, 0x69, 0x64, 0x65, 0x6f,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x69, 0x73, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x68, 0x61, 0x32, 0x35, 0x36, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x73, 0x68, 0x61, 0x32, 0x35, 0x36, 0x12, 0x23, 0x0a, 0x0d, 0x68, 0x61, 0x73, 0x5f, 0x74,
	0x68, 0x75, 0x6d, 0x62, 0x6e, 0x61, 0x69, 0x6c, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c,
	0x68, 0x61, 0x73, 0x54, 0x68, 0x75, 0x6d, 0x62, 0x6e, 0x61, 0x69, 0x6c, 0x12, 0x16, 0x0a, 0x06,
	0x66, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x6f,
	0x6c, 0x64, 0x65, 0x72, 0x22, 0x5b, 0x0a, 0x0e, 0x4c, 0x69, 0x73, 0x74, 0x46, 0x69, 0x6c, 0x65,
	0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x2f, 0x0a, 0x05, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x73, 0x6e, 0x61, 0x70, 0x68, 0x61, 0x76, 0x65,
	0x6e, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x74, 0x65, 0x6d,
	0x52, 0x05, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x66, 0x6f, 0x6c, 0x64, 0x65,
	0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x66, 0x6f, 0x6c, 0x64, 0x65, 0x72,
	0x73, 0x22, 0x3e, 0x0a, 0x10, 0x54, 0x68, 0x75, 0x6d, 0x62, 0x6e, 0x61, 0x69, 0x6c, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x68, 0x61,
	0x32, 0x35, 0x36, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x68, 0x61, 0x32, 0x35,
	0x36, 0x22, 0x6b, 0x0a, 0x0e, 0x54, 0x68, 0x75, 0x6d, 0x62, 0x6e, 0x61, 0x69, 0x6c, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x1b, 0x0a, 0x09, 0x6d,
	0x69, 0x6d, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x6d, 0x69, 0x6d, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x6f, 0x75, 0x6e,
	0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x22, 0x75,
	0x0a, 0x16, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x54, 0x68, 0x75, 0x6d, 0x62, 0x6e, 0x61, 0x69,
	0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x68, 0x61, 0x32, 0x35, 0x36, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x68,
	0x61, 0x32, 0x35, 0x36, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x69, 0x6d, 0x65,
	0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x69, 0x6d,
	0x65, 0x54, 0x79, 0x70, 0x65, 0x22, 0x30, 0x0a, 0x14, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x54,
	0x68, 0x75, 0x6d, 0x62, 0x6e, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x5e, 0x0a, 0x11, 0x4d, 0x65, 0x64, 0x69, 0x61,
	0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68,
	0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x62, 0x79, 0x74, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x42, 0x79, 0x74, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x22, 0x57, 0x0a, 0x0a, 0x4d, 0x65, 0x64, 0x69, 0x61,
	0x43, 0x68, 0x75, 0x6e, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x53, 0x69, 0x7a, 0x65,
	0x22, 0x29, 0x0a, 0x13, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x46, 0x69, 0x6c, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x22, 0x4c, 0x0a, 0x0a, 0x56,
	0x65, 0x72, 0x69, 0x66, 0x79, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74,
	0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x12, 0x0a,
	0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x73, 0x69, 0x7a,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x68, 0x61, 0x32, 0x35, 0x36, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x73, 0x68, 0x61, 0x32, 0x35, 0x36, 0x22, 0x41, 0x0a, 0x12, 0x56, 0x65, 0x72,
	0x69, 0x66, 0x79, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x2b, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15,
	0x2e, 0x73, 0x6e, 0x61, 0x70, 0x68, 0x61, 0x76, 0x65, 0x6e, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66,
	0x79, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x82, 0x01, 0x0a,
	0x0e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x64, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70,
	0x61, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x78, 0x69, 0x73, 0x74, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x06, 0x65, 0x78, 0x69, 0x73, 0x74, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x73,
	0x69, 0x7a, 0x65, 0x5f, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x0b, 0x73, 0x69, 0x7a, 0x65, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x65, 0x73, 0x12, 0x21,
	0x0a, 0x0c, 0x68, 0x61, 0x73, 0x68, 0x5f, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x65, 0x73, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x68, 0x61, 0x73, 0x68, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x65,
	0x73, 0x22, 0x47, 0x0a, 0x10, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x46, 0x69, 0x6c, 0x65, 0x73,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x33, 0x0a, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x73, 0x6e, 0x61, 0x70, 0x68, 0x61, 0x76,
	0x65, 0x6e, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x64, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x52, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x32, 0x9b, 0x05, 0x0a, 0x09, 0x53,
	0x6e, 0x61, 0x70, 0x48, 0x61, 0x76, 0x65, 0x6e, 0x12, 0x36, 0x0a, 0x04, 0x50, 0x69, 0x6e, 0x67,
	0x12, 0x16, 0x2e, 0x73, 0x6e, 0x61, 0x70, 0x68, 0x61, 0x76, 0x65, 0x6e, 0x2e, 0x50, 0x69, 0x6e,
	0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x73, 0x6e, 0x61, 0x70, 0x68,
	0x61, 0x76, 0x65, 0x6e, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00,
	0x12, 0x4a, 0x0a, 0x0c, 0x53, 0x65, 0x6e, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x1a, 0x2e, 0x73, 0x6e, 0x61, 0x70, 0x68, 0x61, 0x76, 0x65, 0x6e, 0x2e, 0x46, 0x69, 0x6c,
	0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x73,
	0x6e, 0x61, 0x70, 0x68, 0x61, 0x76, 0x65, 0x6e, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x12, 0x3b, 0x0a, 0x09,
	0x53, 0x65, 0x6e, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x12, 0x14, 0x2e, 0x73, 0x6e, 0x61, 0x70,
	0x68, 0x61, 0x76, 0x65, 0x6e, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x1a,
	0x14, 0x2e, 0x73, 0x6e, 0x61, 0x70, 0x68, 0x61, 0x76, 0x65, 0x6e, 0x2e, 0x46, 0x69, 0x6c, 0x65,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x28, 0x01, 0x12, 0x4b, 0x0a, 0x0f, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x12, 0x1b, 0x2e, 0x73,
	0x6e, 0x61, 0x70, 0x68, 0x61, 0x76, 0x65, 0x6e, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x46, 0x69, 0x6c,
	0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x73, 0x6e, 0x61, 0x70,
	0x68, 0x61, 0x76, 0x65, 0x6e, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x48, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x54, 0x68, 0x75,
	0x6d, 0x62, 0x6e, 0x61, 0x69, 0x6c, 0x12, 0x1b, 0x2e, 0x73, 0x6e, 0x61, 0x70, 0x68, 0x61, 0x76,
	0x65, 0x6e, 0x2e, 0x54, 0x68, 0x75, 0x6d, 0x62, 0x6e, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x73, 0x6e, 0x61, 0x70, 0x68, 0x61, 0x76, 0x65, 0x6e, 0x2e,
	0x54, 0x68, 0x75, 0x6d, 0x62, 0x6e, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00,
	0x12, 0x57, 0x0a, 0x0f, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x54, 0x68, 0x75, 0x6d, 0x62, 0x6e,
	0x61, 0x69, 0x6c, 0x12, 0x21, 0x2e, 0x73, 0x6e, 0x61, 0x70, 0x68, 0x61, 0x76, 0x65, 0x6e, 0x2e,
	0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x54, 0x68, 0x75, 0x6d, 0x62, 0x6e, 0x61, 0x69, 0x6c, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x73, 0x6e, 0x61, 0x70, 0x68, 0x61, 0x76,
	0x65, 0x6e, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x54, 0x68, 0x75, 0x6d, 0x62, 0x6e, 0x61,
	0x69, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x46, 0x0a, 0x0b, 0x53, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x12, 0x1c, 0x2e, 0x73, 0x6e, 0x61, 0x70, 0x68,
	0x61, 0x76, 0x65, 0x6e, 0x2e, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x73, 0x6e, 0x61, 0x70, 0x68, 0x61, 0x76,
	0x65, 0x6e, 0x2e, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x22, 0x00, 0x30,
	0x01, 0x12, 0x48, 0x0a, 0x0c, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x46, 0x69, 0x6c,
	0x65, 0x12, 0x1e, 0x2e, 0x73, 0x6e, 0x61, 0x70, 0x68, 0x61, 0x76, 0x65, 0x6e, 0x2e, 0x44, 0x6f,
	0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x14, 0x2e, 0x73, 0x6e, 0x61, 0x70, 0x68, 0x61, 0x76, 0x65, 0x6e, 0x2e, 0x46, 0x69,
	0x6c, 0x65, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x22, 0x00, 0x30, 0x01, 0x12, 0x4b, 0x0a, 0x0b, 0x56,
	0x65, 0x72, 0x69, 0x66, 0x79, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x12, 0x1d, 0x2e, 0x73, 0x6e, 0x61,
	0x70, 0x68, 0x61, 0x76, 0x65, 0x6e, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x46, 0x69, 0x6c,
	0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x73, 0x6e, 0x61, 0x70,
	0x68, 0x61, 0x76, 0x65, 0x6e, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x46, 0x69, 0x6c, 0x65,
	0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x1b, 0x0a, 0x0d, 0x61, 0x70, 0x70, 0x2e,
	0x73, 0x6e, 0x61, 0x70, 0x68, 0x61, 0x76, 0x65, 0x6e, 0x5a, 0x0a, 0x2f, 0x73, 0x6e, 0x61, 0x70,
	0x68, 0x61, 0x76, 0x65, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_snaphaven_snaphaven_proto_rawDescOnce sync.Once
	file_snaphaven_snaphaven_proto_rawDescData = file_snaphaven_snaphaven_proto_rawDesc
)

func file_snaphaven_snaphaven_proto_rawDescGZIP() []byte {
	file_snaphaven_snaphaven_proto_rawDescOnce.Do(func() {
		file_snaphaven_snaphaven_proto_rawDescData = protoimpl.X.CompressGZIP(file_snaphaven_snaphaven_proto_rawDescData)
	})
	return file_snaphaven_snaphaven_proto_rawDescData
}

var file_snaphaven_snaphaven_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_snaphaven_snaphaven_proto_goTypes = []interface{}{
	(*PingRequest)(nil),            // 0: snaphaven.PingRequest
	(*PingReply)(nil),              // 1: snaphaven.PingReply
	(*FileInfoRequest)(nil),        // 2: snaphaven.FileInfoRequest
	(*FileInfoReply)(nil),          // 3: snaphaven.FileInfoReply
	(*FileChunk)(nil),              // 4: snaphaven.FileChunk
	(*FileReply)(nil),              // 5: snaphaven.FileReply
	(*ListFilesRequest)(nil),       // 6: snaphaven.ListFilesRequest
	(*RemoteFileItem)(nil),         // 7: snaphaven.RemoteFileItem
	(*ListFilesReply)(nil),         // 8: snaphaven.ListFilesReply
	(*ThumbnailRequest)(nil),       // 9: snaphaven.ThumbnailRequest
	(*ThumbnailReply)(nil),         // 10: snaphaven.ThumbnailReply
	(*UploadThumbnailRequest)(nil), // 11: snaphaven.UploadThumbnailRequest
	(*UploadThumbnailReply)(nil),   // 12: snaphaven.UploadThumbnailReply
	(*MediaRangeRequest)(nil),      // 13: snaphaven.MediaRangeRequest
	(*MediaChunk)(nil),             // 14: snaphaven.MediaChunk
	(*DownloadFileRequest)(nil),    // 15: snaphaven.DownloadFileRequest
	(*VerifyItem)(nil),             // 16: snaphaven.VerifyItem
	(*VerifyFilesRequest)(nil),     // 17: snaphaven.VerifyFilesRequest
	(*VerifiedResult)(nil),         // 18: snaphaven.VerifiedResult
	(*VerifyFilesReply)(nil),       // 19: snaphaven.VerifyFilesReply
}
var file_snaphaven_snaphaven_proto_depIdxs = []int32{
	7,  // 0: snaphaven.ListFilesReply.files:type_name -> snaphaven.RemoteFileItem
	16, // 1: snaphaven.VerifyFilesRequest.items:type_name -> snaphaven.VerifyItem
	18, // 2: snaphaven.VerifyFilesReply.results:type_name -> snaphaven.VerifiedResult
	0,  // 3: snaphaven.SnapHaven.Ping:input_type -> snaphaven.PingRequest
	2,  // 4: snaphaven.SnapHaven.SendFileInfo:input_type -> snaphaven.FileInfoRequest
	4,  // 5: snaphaven.SnapHaven.SendFiles:input_type -> snaphaven.FileChunk
	6,  // 6: snaphaven.SnapHaven.ListRemoteFiles:input_type -> snaphaven.ListFilesRequest
	9,  // 7: snaphaven.SnapHaven.GetThumbnail:input_type -> snaphaven.ThumbnailRequest
	11, // 8: snaphaven.SnapHaven.UploadThumbnail:input_type -> snaphaven.UploadThumbnailRequest
	13, // 9: snaphaven.SnapHaven.StreamMedia:input_type -> snaphaven.MediaRangeRequest
	15, // 10: snaphaven.SnapHaven.DownloadFile:input_type -> snaphaven.DownloadFileRequest
	17, // 11: snaphaven.SnapHaven.VerifyFiles:input_type -> snaphaven.VerifyFilesRequest
	1,  // 12: snaphaven.SnapHaven.Ping:output_type -> snaphaven.PingReply
	3,  // 13: snaphaven.SnapHaven.SendFileInfo:output_type -> snaphaven.FileInfoReply
	5,  // 14: snaphaven.SnapHaven.SendFiles:output_type -> snaphaven.FileReply
	8,  // 15: snaphaven.SnapHaven.ListRemoteFiles:output_type -> snaphaven.ListFilesReply
	10, // 16: snaphaven.SnapHaven.GetThumbnail:output_type -> snaphaven.ThumbnailReply
	12, // 17: snaphaven.SnapHaven.UploadThumbnail:output_type -> snaphaven.UploadThumbnailReply
	14, // 18: snaphaven.SnapHaven.StreamMedia:output_type -> snaphaven.MediaChunk
	4,  // 19: snaphaven.SnapHaven.DownloadFile:output_type -> snaphaven.FileChunk
	19, // 20: snaphaven.SnapHaven.VerifyFiles:output_type -> snaphaven.VerifyFilesReply
	12, // [12:21] is the sub-list for method output_type
	3,  // [3:12] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_snaphaven_snaphaven_proto_init() }
func file_snaphaven_snaphaven_proto_init() {
	if File_snaphaven_snaphaven_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_snaphaven_snaphaven_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_snaphaven_snaphaven_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_snaphaven_snaphaven_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_snaphaven_snaphaven_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileInfoReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_snaphaven_snaphaven_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileChunk); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_snaphaven_snaphaven_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_snaphaven_snaphaven_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListFilesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_snaphaven_snaphaven_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoteFileItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_snaphaven_snaphaven_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListFilesReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_snaphaven_snaphaven_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ThumbnailRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_snaphaven_snaphaven_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ThumbnailReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_snaphaven_snaphaven_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadThumbnailRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_snaphaven_snaphaven_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadThumbnailReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_snaphaven_snaphaven_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MediaRangeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_snaphaven_snaphaven_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MediaChunk); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_snaphaven_snaphaven_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DownloadFileRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_snaphaven_snaphaven_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_snaphaven_snaphaven_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyFilesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_snaphaven_snaphaven_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifiedResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_snaphaven_snaphaven_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyFilesReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_snaphaven_snaphaven_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_snaphaven_snaphaven_proto_goTypes,
		DependencyIndexes: file_snaphaven_snaphaven_proto_depIdxs,
		MessageInfos:      file_snaphaven_snaphaven_proto_msgTypes,
	}.Build()
	File_snaphaven_snaphaven_proto = out.File
	file_snaphaven_snaphaven_proto_rawDesc = nil
	file_snaphaven_snaphaven_proto_goTypes = nil
	file_snaphaven_snaphaven_proto_depIdxs = nil
}
