// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: snaphaven/snaphaven.proto

package snaphaven

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SnapHavenClient is the client API for SnapHaven service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SnapHavenClient interface {
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingReply, error)
	SendFileInfo(ctx context.Context, opts ...grpc.CallOption) (SnapHaven_SendFileInfoClient, error)
	SendFiles(ctx context.Context, opts ...grpc.CallOption) (SnapHaven_SendFilesClient, error)
	// Remote PC Vault & Catalog
	ListRemoteFiles(ctx context.Context, in *ListFilesRequest, opts ...grpc.CallOption) (*ListFilesReply, error)
	GetThumbnail(ctx context.Context, in *ThumbnailRequest, opts ...grpc.CallOption) (*ThumbnailReply, error)
	UploadThumbnail(ctx context.Context, in *UploadThumbnailRequest, opts ...grpc.CallOption) (*UploadThumbnailReply, error)
	// Video Streaming & On-Demand Download
	StreamMedia(ctx context.Context, in *MediaRangeRequest, opts ...grpc.CallOption) (SnapHaven_StreamMediaClient, error)
	DownloadFile(ctx context.Context, in *DownloadFileRequest, opts ...grpc.CallOption) (SnapHaven_DownloadFileClient, error)
	// Storage Cleaner Live Safety Verification
	VerifyFiles(ctx context.Context, in *VerifyFilesRequest, opts ...grpc.CallOption) (*VerifyFilesReply, error)
}

type snapHavenClient struct {
	cc grpc.ClientConnInterface
}

func NewSnapHavenClient(cc grpc.ClientConnInterface) SnapHavenClient {
	return &snapHavenClient{cc}
}

func (c *snapHavenClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingReply, error) {
	out := new(PingReply)
	err := c.cc.Invoke(ctx, "/snaphaven.SnapHaven/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *snapHavenClient) SendFileInfo(ctx context.Context, opts ...grpc.CallOption) (SnapHaven_SendFileInfoClient, error) {
	stream, err := c.cc.NewStream(ctx, &SnapHaven_ServiceDesc.Streams[0], "/snaphaven.SnapHaven/SendFileInfo", opts...)
	if err != nil {
		return nil, err
	}
	x := &snapHavenSendFileInfoClient{stream}
	return x, nil
}

type SnapHaven_SendFileInfoClient interface {
	Send(*FileInfoRequest) error
	Recv() (*FileInfoReply, error)
	grpc.ClientStream
}

type snapHavenSendFileInfoClient struct {
	grpc.ClientStream
}

func (x *snapHavenSendFileInfoClient) Send(m *FileInfoRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *snapHavenSendFileInfoClient) Recv() (*FileInfoReply, error) {
	m := new(FileInfoReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *snapHavenClient) SendFiles(ctx context.Context, opts ...grpc.CallOption) (SnapHaven_SendFilesClient, error) {
	stream, err := c.cc.NewStream(ctx, &SnapHaven_ServiceDesc.Streams[1], "/snaphaven.SnapHaven/SendFiles", opts...)
	if err != nil {
		return nil, err
	}
	x := &snapHavenSendFilesClient{stream}
	return x, nil
}

type SnapHaven_SendFilesClient interface {
	Send(*FileChunk) error
	CloseAndRecv() (*FileReply, error)
	grpc.ClientStream
}

type snapHavenSendFilesClient struct {
	grpc.ClientStream
}

func (x *snapHavenSendFilesClient) Send(m *FileChunk) error {
	return x.ClientStream.SendMsg(m)
}

func (x *snapHavenSendFilesClient) CloseAndRecv() (*FileReply, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(FileReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *snapHavenClient) ListRemoteFiles(ctx context.Context, in *ListFilesRequest, opts ...grpc.CallOption) (*ListFilesReply, error) {
	out := new(ListFilesReply)
	err := c.cc.Invoke(ctx, "/snaphaven.SnapHaven/ListRemoteFiles", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *snapHavenClient) GetThumbnail(ctx context.Context, in *ThumbnailRequest, opts ...grpc.CallOption) (*ThumbnailReply, error) {
	out := new(ThumbnailReply)
	err := c.cc.Invoke(ctx, "/snaphaven.SnapHaven/GetThumbnail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *snapHavenClient) UploadThumbnail(ctx context.Context, in *UploadThumbnailRequest, opts ...grpc.CallOption) (*UploadThumbnailReply, error) {
	out := new(UploadThumbnailReply)
	err := c.cc.Invoke(ctx, "/snaphaven.SnapHaven/UploadThumbnail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *snapHavenClient) StreamMedia(ctx context.Context, in *MediaRangeRequest, opts ...grpc.CallOption) (SnapHaven_StreamMediaClient, error) {
	stream, err := c.cc.NewStream(ctx, &SnapHaven_ServiceDesc.Streams[2], "/snaphaven.SnapHaven/StreamMedia", opts...)
	if err != nil {
		return nil, err
	}
	x := &snapHavenStreamMediaClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SnapHaven_StreamMediaClient interface {
	Recv() (*MediaChunk, error)
	grpc.ClientStream
}

type snapHavenStreamMediaClient struct {
	grpc.ClientStream
}

func (x *snapHavenStreamMediaClient) Recv() (*MediaChunk, error) {
	m := new(MediaChunk)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *snapHavenClient) DownloadFile(ctx context.Context, in *DownloadFileRequest, opts ...grpc.CallOption) (SnapHaven_DownloadFileClient, error) {
	stream, err := c.cc.NewStream(ctx, &SnapHaven_ServiceDesc.Streams[3], "/snaphaven.SnapHaven/DownloadFile", opts...)
	if err != nil {
		return nil, err
	}
	x := &snapHavenDownloadFileClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SnapHaven_DownloadFileClient interface {
	Recv() (*FileChunk, error)
	grpc.ClientStream
}

type snapHavenDownloadFileClient struct {
	grpc.ClientStream
}

func (x *snapHavenDownloadFileClient) Recv() (*FileChunk, error) {
	m := new(FileChunk)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *snapHavenClient) VerifyFiles(ctx context.Context, in *VerifyFilesRequest, opts ...grpc.CallOption) (*VerifyFilesReply, error) {
	out := new(VerifyFilesReply)
	err := c.cc.Invoke(ctx, "/snaphaven.SnapHaven/VerifyFiles", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SnapHavenServer is the server API for SnapHaven service.
// All implementations must embed UnimplementedSnapHavenServer
// for forward compatibility
type SnapHavenServer interface {
	Ping(context.Context, *PingRequest) (*PingReply, error)
	SendFileInfo(SnapHaven_SendFileInfoServer) error
	SendFiles(SnapHaven_SendFilesServer) error
	// Remote PC Vault & Catalog
	ListRemoteFiles(context.Context, *ListFilesRequest) (*ListFilesReply, error)
	GetThumbnail(context.Context, *ThumbnailRequest) (*ThumbnailReply, error)
	UploadThumbnail(context.Context, *UploadThumbnailRequest) (*UploadThumbnailReply, error)
	// Video Streaming & On-Demand Download
	StreamMedia(*MediaRangeRequest, SnapHaven_StreamMediaServer) error
	DownloadFile(*DownloadFileRequest, SnapHaven_DownloadFileServer) error
	// Storage Cleaner Live Safety Verification
	VerifyFiles(context.Context, *VerifyFilesRequest) (*VerifyFilesReply, error)
	mustEmbedUnimplementedSnapHavenServer()
}

// UnimplementedSnapHavenServer must be embedded to have forward compatible implementations.
type UnimplementedSnapHavenServer struct {
}

func (UnimplementedSnapHavenServer) Ping(context.Context, *PingRequest) (*PingReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedSnapHavenServer) SendFileInfo(SnapHaven_SendFileInfoServer) error {
	return status.Errorf(codes.Unimplemented, "method SendFileInfo not implemented")
}
func (UnimplementedSnapHavenServer) SendFiles(SnapHaven_SendFilesServer) error {
	return status.Errorf(codes.Unimplemented, "method SendFiles not implemented")
}
func (UnimplementedSnapHavenServer) ListRemoteFiles(context.Context, *ListFilesRequest) (*ListFilesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRemoteFiles not implemented")
}
func (UnimplementedSnapHavenServer) GetThumbnail(context.Context, *ThumbnailRequest) (*ThumbnailReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetThumbnail not implemented")
}
func (UnimplementedSnapHavenServer) UploadThumbnail(context.Context, *UploadThumbnailRequest) (*UploadThumbnailReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadThumbnail not implemented")
}
func (UnimplementedSnapHavenServer) StreamMedia(*MediaRangeRequest, SnapHaven_StreamMediaServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamMedia not implemented")
}
func (UnimplementedSnapHavenServer) DownloadFile(*DownloadFileRequest, SnapHaven_DownloadFileServer) error {
	return status.Errorf(codes.Unimplemented, "method DownloadFile not implemented")
}
func (UnimplementedSnapHavenServer) VerifyFiles(context.Context, *VerifyFilesRequest) (*VerifyFilesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyFiles not implemented")
}
func (UnimplementedSnapHavenServer) mustEmbedUnimplementedSnapHavenServer() {}

// UnsafeSnapHavenServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SnapHavenServer will
// result in compilation errors.
type UnsafeSnapHavenServer interface {
	mustEmbedUnimplementedSnapHavenServer()
}

func RegisterSnapHavenServer(s grpc.ServiceRegistrar, srv SnapHavenServer) {
	s.RegisterService(&SnapHaven_ServiceDesc, srv)
}

func _SnapHaven_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnapHavenServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/snaphaven.SnapHaven/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnapHavenServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SnapHaven_SendFileInfo_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SnapHavenServer).SendFileInfo(&snapHavenSendFileInfoServer{stream})
}

type SnapHaven_SendFileInfoServer interface {
	Send(*FileInfoReply) error
	Recv() (*FileInfoRequest, error)
	grpc.ServerStream
}

type snapHavenSendFileInfoServer struct {
	grpc.ServerStream
}

func (x *snapHavenSendFileInfoServer) Send(m *FileInfoReply) error {
	return x.ServerStream.SendMsg(m)
}

func (x *snapHavenSendFileInfoServer) Recv() (*FileInfoRequest, error) {
	m := new(FileInfoRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _SnapHaven_SendFiles_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SnapHavenServer).SendFiles(&snapHavenSendFilesServer{stream})
}

type SnapHaven_SendFilesServer interface {
	SendAndClose(*FileReply) error
	Recv() (*FileChunk, error)
	grpc.ServerStream
}

type snapHavenSendFilesServer struct {
	grpc.ServerStream
}

func (x *snapHavenSendFilesServer) SendAndClose(m *FileReply) error {
	return x.ServerStream.SendMsg(m)
}

func (x *snapHavenSendFilesServer) Recv() (*FileChunk, error) {
	m := new(FileChunk)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _SnapHaven_ListRemoteFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnapHavenServer).ListRemoteFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/snaphaven.SnapHaven/ListRemoteFiles",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnapHavenServer).ListRemoteFiles(ctx, req.(*ListFilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SnapHaven_GetThumbnail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ThumbnailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnapHavenServer).GetThumbnail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/snaphaven.SnapHaven/GetThumbnail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnapHavenServer).GetThumbnail(ctx, req.(*ThumbnailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SnapHaven_UploadThumbnail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadThumbnailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnapHavenServer).UploadThumbnail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/snaphaven.SnapHaven/UploadThumbnail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnapHavenServer).UploadThumbnail(ctx, req.(*UploadThumbnailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SnapHaven_StreamMedia_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(MediaRangeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SnapHavenServer).StreamMedia(m, &snapHavenStreamMediaServer{stream})
}

type SnapHaven_StreamMediaServer interface {
	Send(*MediaChunk) error
	grpc.ServerStream
}

type snapHavenStreamMediaServer struct {
	grpc.ServerStream
}

func (x *snapHavenStreamMediaServer) Send(m *MediaChunk) error {
	return x.ServerStream.SendMsg(m)
}

func _SnapHaven_DownloadFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DownloadFileRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SnapHavenServer).DownloadFile(m, &snapHavenDownloadFileServer{stream})
}

type SnapHaven_DownloadFileServer interface {
	Send(*FileChunk) error
	grpc.ServerStream
}

type snapHavenDownloadFileServer struct {
	grpc.ServerStream
}

func (x *snapHavenDownloadFileServer) Send(m *FileChunk) error {
	return x.ServerStream.SendMsg(m)
}

func _SnapHaven_VerifyFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyFilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnapHavenServer).VerifyFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/snaphaven.SnapHaven/VerifyFiles",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnapHavenServer).VerifyFiles(ctx, req.(*VerifyFilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SnapHaven_ServiceDesc is the grpc.ServiceDesc for SnapHaven service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SnapHaven_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "snaphaven.SnapHaven",
	HandlerType: (*SnapHavenServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _SnapHaven_Ping_Handler,
		},
		{
			MethodName: "ListRemoteFiles",
			Handler:    _SnapHaven_ListRemoteFiles_Handler,
		},
		{
			MethodName: "GetThumbnail",
			Handler:    _SnapHaven_GetThumbnail_Handler,
		},
		{
			MethodName: "UploadThumbnail",
			Handler:    _SnapHaven_UploadThumbnail_Handler,
		},
		{
			MethodName: "VerifyFiles",
			Handler:    _SnapHaven_VerifyFiles_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SendFileInfo",
			Handler:       _SnapHaven_SendFileInfo_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "SendFiles",
			Handler:       _SnapHaven_SendFiles_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "StreamMedia",
			Handler:       _SnapHaven_StreamMedia_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "DownloadFile",
			Handler:       _SnapHaven_DownloadFile_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "snaphaven/snaphaven.proto",
}
