// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: filesync/filesync.proto

package filesync

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FileSyncClient is the client API for FileSync service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FileSyncClient interface {
	SendFileInfo(ctx context.Context, opts ...grpc.CallOption) (FileSync_SendFileInfoClient, error)
	SendFiles(ctx context.Context, opts ...grpc.CallOption) (FileSync_SendFilesClient, error)
}

type fileSyncClient struct {
	cc grpc.ClientConnInterface
}

func NewFileSyncClient(cc grpc.ClientConnInterface) FileSyncClient {
	return &fileSyncClient{cc}
}

func (c *fileSyncClient) SendFileInfo(ctx context.Context, opts ...grpc.CallOption) (FileSync_SendFileInfoClient, error) {
	stream, err := c.cc.NewStream(ctx, &FileSync_ServiceDesc.Streams[0], "/filesync.FileSync/SendFileInfo", opts...)
	if err != nil {
		return nil, err
	}
	x := &fileSyncSendFileInfoClient{stream}
	return x, nil
}

type FileSync_SendFileInfoClient interface {
	Send(*FileInfoRequest) error
	Recv() (*FileInfoReply, error)
	grpc.ClientStream
}

type fileSyncSendFileInfoClient struct {
	grpc.ClientStream
}

func (x *fileSyncSendFileInfoClient) Send(m *FileInfoRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *fileSyncSendFileInfoClient) Recv() (*FileInfoReply, error) {
	m := new(FileInfoReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *fileSyncClient) SendFiles(ctx context.Context, opts ...grpc.CallOption) (FileSync_SendFilesClient, error) {
	stream, err := c.cc.NewStream(ctx, &FileSync_ServiceDesc.Streams[1], "/filesync.FileSync/SendFiles", opts...)
	if err != nil {
		return nil, err
	}
	x := &fileSyncSendFilesClient{stream}
	return x, nil
}

type FileSync_SendFilesClient interface {
	Send(*FileChunk) error
	CloseAndRecv() (*FileReply, error)
	grpc.ClientStream
}

type fileSyncSendFilesClient struct {
	grpc.ClientStream
}

func (x *fileSyncSendFilesClient) Send(m *FileChunk) error {
	return x.ClientStream.SendMsg(m)
}

func (x *fileSyncSendFilesClient) CloseAndRecv() (*FileReply, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(FileReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// FileSyncServer is the server API for FileSync service.
// All implementations must embed UnimplementedFileSyncServer
// for forward compatibility
type FileSyncServer interface {
	SendFileInfo(FileSync_SendFileInfoServer) error
	SendFiles(FileSync_SendFilesServer) error
	mustEmbedUnimplementedFileSyncServer()
}

// UnimplementedFileSyncServer must be embedded to have forward compatible implementations.
type UnimplementedFileSyncServer struct {
}

func (UnimplementedFileSyncServer) SendFileInfo(FileSync_SendFileInfoServer) error {
	return status.Errorf(codes.Unimplemented, "method SendFileInfo not implemented")
}
func (UnimplementedFileSyncServer) SendFiles(FileSync_SendFilesServer) error {
	return status.Errorf(codes.Unimplemented, "method SendFiles not implemented")
}
func (UnimplementedFileSyncServer) mustEmbedUnimplementedFileSyncServer() {}

// UnsafeFileSyncServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FileSyncServer will
// result in compilation errors.
type UnsafeFileSyncServer interface {
	mustEmbedUnimplementedFileSyncServer()
}

func RegisterFileSyncServer(s grpc.ServiceRegistrar, srv FileSyncServer) {
	s.RegisterService(&FileSync_ServiceDesc, srv)
}

func _FileSync_SendFileInfo_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FileSyncServer).SendFileInfo(&fileSyncSendFileInfoServer{stream})
}

type FileSync_SendFileInfoServer interface {
	Send(*FileInfoReply) error
	Recv() (*FileInfoRequest, error)
	grpc.ServerStream
}

type fileSyncSendFileInfoServer struct {
	grpc.ServerStream
}

func (x *fileSyncSendFileInfoServer) Send(m *FileInfoReply) error {
	return x.ServerStream.SendMsg(m)
}

func (x *fileSyncSendFileInfoServer) Recv() (*FileInfoRequest, error) {
	m := new(FileInfoRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _FileSync_SendFiles_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FileSyncServer).SendFiles(&fileSyncSendFilesServer{stream})
}

type FileSync_SendFilesServer interface {
	SendAndClose(*FileReply) error
	Recv() (*FileChunk, error)
	grpc.ServerStream
}

type fileSyncSendFilesServer struct {
	grpc.ServerStream
}

func (x *fileSyncSendFilesServer) SendAndClose(m *FileReply) error {
	return x.ServerStream.SendMsg(m)
}

func (x *fileSyncSendFilesServer) Recv() (*FileChunk, error) {
	m := new(FileChunk)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// FileSync_ServiceDesc is the grpc.ServiceDesc for FileSync service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FileSync_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "filesync.FileSync",
	HandlerType: (*FileSyncServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SendFileInfo",
			Handler:       _FileSync_SendFileInfo_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "SendFiles",
			Handler:       _FileSync_SendFiles_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "filesync/filesync.proto",
}
